version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq:/var/lib/rabbitmq/
        
  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - 5080:5080
      - 6080:6080
      - 8080:8080
      - 9080:9080
      - 8000:8000
    volumes:
      - dgraph:/dgraph

  cardano-node-ogmios:
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
      cache_from: [cardanosolutions/cardano-node-ogmios:latest]
      context: ../../ogmios
    image: cardanosolutions/cardano-node-ogmios:${CARDANO_NODE_OGMIOS_VERSION:-v4.1.0}-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-db:/db

  chain-follower:
    build:
      args:
        - NETWORK=${NETWORK:-mainnet}
      cache_from: [inputoutput/cardano-graphql-chain-follower:latest]
      context: ../../
      target: chain-follower
    image: inputoutput/cardano-graphql-chain-follower:${CARDANO_GRAPHQL_VERSION:-6.1.0}-${NETWORK:-mainnet}
    environment:
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-db:
  dgraph:
  rabbitmq:
