version: '3.7'
services:
  api-server:
    build:
      context: ..
      target: server
    environment:
      - CACHE_ENABLED=true
      - HASURA_URI=http://hasura:8080/v1/graphql
    ports:
      - ${API_PORT:-3100}:3100
  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.6.cli-migrations
    depends_on:
      - "postgres"
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://nix:postgres@postgres:5432/cexplorer
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ../hasura/migrations:/hasura-migrations
    ports:
      - "8090:8080"
  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=nix
      - POSTGRES_DB=cexplorer
    volumes:
      - ../test/postgres/init:/docker-entrypoint-initdb.d
